config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :trips do
  member do
    get "vote"
  end
end

  resources :participants

  resources :activities do
  member do
    get "vote"
  end
end

  resources :destinations do
  member do
    get "vote"
  end
end

  resources :luggages do
  member do
    get "vote"
  end
end

  root 'landings#index'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :activities
  has_many :participants
  has_many :destinations
  has_many :luggages
  acts_as_votable 
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy, :vote]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @trip.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:title, :description, :meetup_at, :meetup_location)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for @trip, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :meetup_at, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :meetup_at, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :meetup_location, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :meetup_location, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  trips_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/trips/edit.html.erb
<%- model_class = Trip -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Trip %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trips/index.html.erb
<%- model_class = Trip -%>
<div class="page-header">
  <h1><%=t '.title', :default => Trip %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:meetup_at) %></th>
      <th><%= model_class.human_attribute_name(:meetup_location) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.id %></td>
        <td><%= trip.title %></td>
        <td><%= trip.description %></td>
        <td><%= trip.meetup_at %></td>
        <td><%= trip.meetup_location %></td>
        <td><%=l trip.created_at, format: :long %></td>
        <td>
          <%= link_to "Edit", trip_path(trip), :class => 'btn btn-default btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" %>
          <%= link_to "Delete", trip_path(trip), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-default btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_trip_path,
            :class => 'btn btn-primary' %>

app/views/trips/new.html.erb
<%- model_class = Trip -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Trip %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trips/show.html.erb
<%- model_class = Trip -%>
<div class="page-header">
  <h1><%=t '.title', :default => Trip %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @trip.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @trip.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:meetup_at) %></dt>
      <dd><pre class="prettyprint"><%= @trip.meetup_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:meetup_location) %></dt>
      <dd><pre class="prettyprint"><%= @trip.meetup_location %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              trips_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_trip_path(@trip), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              trip_path(@trip),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>