config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :trips do
  member do
    get "vote"
  end
end

  resources :participants

  resources :activities do
  member do
    get "vote"
  end
end

  resources :destinations do
  member do
    get "vote"
  end
end

  resources :luggages do
  member do
    get "vote"
  end
end

  root 'landings#index'

end

app/models/luggage.rb
class Luggage < ActiveRecord::Base
  belongs_to :trip
  belongs_to :participant
  belongs_to :responsible_person, class_name: "Participant", foreign_key: :taken_care_of_by_id
  acts_as_votable
end

app/controllers/luggages_controller.rb
class LuggagesController < ApplicationController
  before_action :set_luggage, only: [:show, :edit, :update, :destroy, :vote]

  # GET /luggages
  # GET /luggages.json
  def index
    @luggages = Luggage.all
  end

  # GET /luggages/1
  # GET /luggages/1.json
  def show
  end

  # GET /luggages/new
  def new
    @luggage = Luggage.new
  end

  # GET /luggages/1/edit
  def edit
  end

  # POST /luggages
  # POST /luggages.json
  def create
    @luggage = Luggage.new(luggage_params)

    respond_to do |format|
      if @luggage.save
        format.html { redirect_to @luggage, notice: 'Luggage was successfully created.' }
        format.json { render :show, status: :created, location: @luggage }
      else
        format.html { render :new }
        format.json { render json: @luggage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /luggages/1
  # PATCH/PUT /luggages/1.json
  def update
    respond_to do |format|
      if @luggage.update(luggage_params)
        format.html { redirect_to @luggage, notice: 'Luggage was successfully updated.' }
        format.json { render :show, status: :ok, location: @luggage }
      else
        format.html { render :edit }
        format.json { render json: @luggage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /luggages/1
  # DELETE /luggages/1.json
  def destroy
    @luggage.destroy
    respond_to do |format|
      format.html { redirect_to luggages_url, notice: 'Luggage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @luggage.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_luggage
      @luggage = Luggage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def luggage_params
      params.require(:luggage).permit(:name, :trip_id, :participant_id, :quantity, :price, :comment, :importance, :taken_care_of, :taken_care_of_by_id)
    end
end

app/helpers/luggages_helper.rb
module LuggagesHelper
end

app/views/luggages/_form.html.slim
= simple_form_for @luggage do |f|
  = f.input :name
  = f.input :comment
  = f.input :quantity
  = f.input :importance
  = f.input :price
  = f.association :participant
  = f.association :responsible_person
  = f.button :submit

app/views/luggages/edit.html.erb
<%- model_class = Luggage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Luggage %></h1>
</div>
<%= render :partial => 'form' %>

app/views/luggages/index.html.slim
- model_class = Luggage
.page-header
  h1= t '.title', :default => Luggage
table.table.table-striped
  thead
    tr
      th ID
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:quantity)
      th= model_class.human_attribute_name(:price)
      th= model_class.human_attribute_name(:importance)
      th= model_class.human_attribute_name(:taken_care_of_by_id)
      th= model_class.human_attribute_name(:created_at)
      th= t '.actions', :default => t("helpers.actions")
  tbody
    - @luggages.each do |luggage|
      tr
        td= luggage.id
        td= luggage.name
        td= luggage.quantity
        td= luggage.price
        td= luggage.importance
        td= luggage.responsible_person.try(:name) || "-"
        td= l luggage.created_at, format: :long
        td
          .btn-group
            = link_to "Details", luggage_path(luggage), :class => 'btn btn-default btn-xs'
            = link_to "Remove", luggage_path(luggage), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-default btn-xs'
  = link_to "New", new_luggage_path, :class => 'btn btn-primary'

app/views/luggages/new.html.erb
<%- model_class = Luggage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Luggage %></h1>
</div>
<%= render :partial => 'form' %>

app/views/luggages/show.html.erb
<%- model_class = Luggage -%>
<div class="page-header">
  <h1><%=t '.title', :default => Luggage %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @luggage.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:quantity) %></dt>
      <dd><pre class="prettyprint"><%= @luggage.quantity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:price) %></dt>
      <dd><pre class="prettyprint"><%= @luggage.price %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:comment) %></dt>
      <dd><pre class="prettyprint"><%= @luggage.comment %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:importance) %></dt>
      <dd><pre class="prettyprint"><%= @luggage.importance %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:taken_care_of) %></dt>
      <dd><pre class="prettyprint"><%= @luggage.taken_care_of %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:taken_care_of_by_id) %></dt>
      <dd><pre class="prettyprint"><%= @luggage.taken_care_of_by_id %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              luggages_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_luggage_path(@luggage), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              luggage_path(@luggage),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>